name: Run API tests
run-name: ${{ github.actor }} is running tests

on:
  push:
    branches:
      - my/update_workflow_api_tests
  workflow_dispatch:
    inputs:
      test_suite_file:
        description: 'Select the test suite xml file'
        required: true
        default: 'regression.xml'
        type: string

jobs:
  run-test:
    name: Run tests and generate Allure Report
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/api-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Set up Java 11
        uses: actions/setup-java@v4.0.0
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Tests
        continue-on-error: true
        run: |
          echo "workspace is ${{ github.workspace }}"
          mvn clean test -DsuiteFile=src/test/resources/suites/${{inputs.test_suite_file}} \
            -DCLIENT_KEY=${{ secrets.CLIENT_KEY }} -DCLIENT_TOKEN=${{ secrets.CLIENT_TOKEN }}

      - name: Setup Allure History
        uses: actions/checkout@v4.1.1
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          allure_results: ${{ github.workspace }}/allure-results
          allure_history: allure-history
          keep_reports: 10


      - name: Publish Allure Report
        if: always()
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Set Job Summary
        run: |
          echo "### The Allure Report below: " >> $GITHUB_STEP_SUMMARY
          echo "#### https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.run_number }}" >> $GITHUB_STEP_SUMMARY
