name: Run API tests
run-name: ${{ github.actor }} is running tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "30 5,17 * * *"

jobs:
  test:
    runs-on: ta-ubuntu-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Run TA tests
        env:
          HTML_RESULT: ${{ github.workspace }}\results
        run: scripts\run-tests.sh

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results\*
